# ===============================
# DATASOURCE & SQL SERVER SETUP
# ===============================
# Chuỗi kết nối đã được thêm instanceName=MAY1 dựa trên ảnh của bạn
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BmsApartmentDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA & HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# ===============================
# SERVER PORT
# ===============================
server.port=8080

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true